### ISSUE TITLE
SW_x configuratoin

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/PaxInstruments-LabWiz-firmware#12]
Should the input button be configured as GPIO_EXTIx?
SW_A PC11
SW_B PC10
SW_C PC7
SW_D PA8
SW_E PB2

![screen shot 2016-08-14 at 21 55 27](https://cloud.githubusercontent.com/assets/281642/17649521/e5eaeb12-6269-11e6-918c-36451cd7edef.png)

**Comment by protological** [comment]
Yes, the buttons should all be EXT, since this is the external interrupt signal.

**Comment by charlespax** [comment]
In the version 0.3 boards I just ordered this is the configuration.
- SW_A is on PC9 and had GPIO_EXTI9
- SW_B is on PA8 and had GPIO_EXTI8
- SW_C is on PA9 and had GPIO_EXTI9
- SW_D is on PB2 and had GPIO_EXTI2
- SW_E is on PB10 and had GPIO_EXTI10
- SW_PWR is on PA0 and had GPIO_EXTI0

SW_A and SW_C are on the same interrupt. Should I move one to another pin in the next revision? PC1 (GPIO_EXTI1) and PC4 (GPIO_EXTI4) are currently unused. I can also swap one out with WIFI_EN (PC7, GPIO_EXTI7).

**Comment by charlespax** [comment]
@protological I believe you already addressed this in the .ioc file.

**Comment by protological** [comment]
Page 209 in the STM32F103 datasheet shows that EXTI interrupts are connected to all ports.  The EXTI number matches the Port number, so EXTI9 is connected to Ports A,B,C,D pin #9.  As long as there are not two inputs on the same EXTI we can detect individual buttons.  

EXTI 1 and 4 would work for SW_C, I would keep everything else where it is.

**Comment by charlespax** [comment]
Swapped WIFI_EN with SW_A to avoid interrupt sharing. Adjusted .ioc file accordingly.
