### ISSUE TITLE
SD_FATFS config

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/PaxInstruments-LabWiz-firmware#14]
What does the "User-defined" checkbox do? What should the configuration be?

![screen shot 2016-08-14 at 22 03 28](https://cloud.githubusercontent.com/assets/281642/17649557/fa3b002e-626a-11e6-80df-95041fc9ae3c.png)

**Comment by protological** [comment]
I am not sure what the user-defined checkbox is for.  There is a ffconf.h file in the include/system/ folder which configures the FatFS library.
